"""empty message

Revision ID: 394f752e85e0
Revises: f1b4741024fe
Create Date: 2020-04-05 10:25:55.413081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394f752e85e0'
down_revision = 'f1b4741024fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('from_where', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'from_where')
    # ### end Alembic commands ###
